extends:
  - eslint:recommended
plugins:
  - promise
  - nodejs

rules:
  no-console: 0
  strict: 0
  indent: 0
  no-extra-semi: 0
  comma-dangle: 0
  space-before-function-paren: 0
  semi: 0
  keyword-spacing: 0
  no-trailing-spaces: 0

parserOptions:
   ecmaVersion: 6
